spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    mongodb:
      uri: mongodb://localhost/springcloud
eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://localhost:7080/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}