spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    mongodb:
      uri: mongodb://localhost/springcloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7080/eureka/
  instance:
    appname: microserviceprovider-a