server:
  port: 7070
spring:
  cloud:
    config:
      server:
        git:
          search-paths: Config-Repo
          uri: https://github.com/supreme94/Spring-Cloud-Example.git
          username: supreme94
          password: lp19920717
  application:
    name: config-server